# Generated by Django 4.2.11 on 2026-02-08 16:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        error_messages={
                            "unique": "Ya existe un usuario con este email."
                        },
                        max_length=255,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "Ya existe un usuario con este nombre."
                        },
                        help_text="Nombre para mostrar. Debe ser único.",
                        max_length=150,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(3)],
                        verbose_name="nombre de usuario",
                    ),
                ),
                (
                    "failed_login_attempts",
                    models.IntegerField(
                        default=0,
                        help_text="Número de intentos de login fallidos consecutivos",
                        verbose_name="intentos fallidos",
                    ),
                ),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Cuenta bloqueada hasta esta fecha/hora",
                        null=True,
                        verbose_name="bloqueado hasta",
                    ),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Dirección IP del último login exitoso",
                        null=True,
                        verbose_name="última IP de login",
                    ),
                ),
                (
                    "last_failed_login_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        null=True,
                        verbose_name="última IP de intento fallido",
                    ),
                ),
                (
                    "password_changed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha del último cambio de contraseña",
                        null=True,
                        verbose_name="contraseña cambiada en",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
            ],
            options={
                "verbose_name": "usuario",
                "verbose_name_plural": "usuarios",
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login Exitoso"),
                            ("logout", "Logout"),
                            ("login_failed", "Intento de Login Fallido"),
                            ("password_change", "Cambio de Contraseña"),
                            ("password_reset", "Reseteo de Contraseña"),
                            ("account_locked", "Cuenta Bloqueada"),
                            ("account_unlocked", "Cuenta Desbloqueada"),
                            ("permission_denied", "Permiso Denegado"),
                            ("token_refresh", "Token Renovado"),
                            ("token_blacklist", "Token Revocado"),
                        ],
                        max_length=50,
                        verbose_name="acción",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="IP desde donde se realizó la acción",
                        verbose_name="dirección IP",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        help_text="Información del navegador/cliente",
                        verbose_name="user agent",
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Información adicional en formato JSON",
                        verbose_name="detalles",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="creado en"
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de auditoría",
                "verbose_name_plural": "registros de auditoría",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código único de permiso (ej: orders.create)",
                        max_length=100,
                        unique=True,
                        verbose_name="código",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre legible del permiso",
                        max_length=200,
                        verbose_name="nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada del permiso",
                        verbose_name="descripción",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        help_text="Módulo al que pertenece (orders, patients, billing, etc.)",
                        max_length=50,
                        verbose_name="módulo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
            ],
            options={
                "verbose_name": "permiso",
                "verbose_name_plural": "permisos",
                "db_table": "permissions",
                "ordering": ["module", "code"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superadmin", "Super Administrador"),
                            ("doctor", "Doctor"),
                            ("lab_technician", "Técnico de Laboratorio"),
                            ("finance_user", "Usuario Financiero"),
                            ("manager", "Gerente"),
                        ],
                        help_text="Rol del usuario que determina sus permisos",
                        max_length=20,
                        verbose_name="rol",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Número de teléfono de contacto",
                        max_length=20,
                        verbose_name="teléfono",
                    ),
                ),
                (
                    "avatar",
                    models.URLField(
                        blank=True,
                        help_text="URL de la imagen de perfil",
                        max_length=500,
                        verbose_name="avatar",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sucursal asignada (null para superadmin)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="branches.branch",
                        verbose_name="sucursal",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "perfil de usuario",
                "verbose_name_plural": "perfiles de usuario",
                "db_table": "user_profiles",
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superadmin", "Super Administrador"),
                            ("doctor", "Doctor"),
                            ("lab_technician", "Técnico de Laboratorio"),
                            ("finance_user", "Usuario Financiero"),
                            ("manager", "Gerente"),
                        ],
                        max_length=20,
                        verbose_name="rol",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.permission",
                        verbose_name="permiso",
                    ),
                ),
            ],
            options={
                "verbose_name": "permiso de rol",
                "verbose_name_plural": "permisos de roles",
                "db_table": "role_permissions",
            },
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(fields=["code"], name="permissions_code_a0a529_idx"),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(fields=["module"], name="permissions_module_2c0512_idx"),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la acción (null para intentos fallidos)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuario",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["role"], name="user_profil_role_fa03e1_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["branch"], name="user_profil_branch__636a1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(fields=["role"], name="role_permis_role_83b50a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together={("role", "permission")},
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "-created_at"], name="audit_logs_user_id_6193b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "-created_at"], name="audit_logs_action_bcaa71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["ip_address", "-created_at"],
                name="audit_logs_ip_addr_190b84_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["-created_at"], name="audit_logs_created_43fcd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_active"], name="users_is_acti_847b48_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["locked_until"], name="users_locked__615cd3_idx"
            ),
        ),
    ]
