# Generated by Django 4.2.11 on 2026-02-08 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la sucursal', max_length=200, verbose_name='nombre')),
                ('code', models.CharField(help_text='Código único de la sucursal (ej: LAB-01)', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='código')),
                ('address', models.TextField(help_text='Dirección física de la sucursal', verbose_name='dirección')),
                ('phone', models.CharField(help_text='Teléfono de contacto', max_length=20, verbose_name='teléfono')),
                ('email', models.EmailField(help_text='Email de contacto de la sucursal', max_length=254, verbose_name='email')),
                ('is_active', models.BooleanField(default=True, help_text='Si la sucursal está actualmente operativa', verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
                'db_table': 'branches',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='branches_code_95622b_idx'), models.Index(fields=['is_active'], name='branches_is_acti_830392_idx')],
            },
        ),
    ]
